@echo off
rem ASCII ONLY. Do not put non-ASCII text in this file.
rem Generated by provision-bot.ts for bot "shop-b" -- do not hand-edit the
rem CONFIG/PORT lines, re-run the provisioner instead.

setlocal
cd /d "%~dp0"

set CONFIG=config/bots/shop-b.json
set SESSIONS_DIR=.sessions
set USERS_FILE=.control\bot-users\shop-b.json
set PORT=8792

where deno >nul 2>&1
if errorlevel 1 (
    echo [x] deno not found on PATH.
    echo     Install: irm https://deno.land/install.ps1 ^| iex
    pause
    exit /b 1
)

if not exist "%CONFIG%" (
    echo [x] %CONFIG% not found -- was it moved or deleted?
    pause
    exit /b 1
)

echo Starting local worker: %CONFIG%  (sessions: %SESSIONS_DIR%, port: %PORT%)
echo Opening http://localhost:%PORT%/account/login
echo Press Ctrl+C to stop for real.
echo.

start "" "http://localhost:%PORT%/account/login"

:run
deno task serve --config "%CONFIG%" --sessions-dir "%SESSIONS_DIR%" --users-file "%USERS_FILE%" --port %PORT% %*
echo.
echo [i] worker stopped -- restarting in 3s (Ctrl+C, then Y, to quit for real)
timeout /t 3 /nobreak >nul
goto run

endlocal
