import { parseArgs } from '@std/cli/parse-args';
import { ConfigError } from '../errors/base.ts';
import { writeErr, writeLine } from './console.ts';

/**
 * Provisions a brand-new, fully separate bot: its own config file and its
 * own port, ready for its own `start-<name>.bat`.
 *
 * This exists because "add a user" turned out to mean "give that person
 * their own LINE bot" — own QR login, own rules, own rooms — not another
 * login on the same shared bot (`admin/users-store.ts`'s docstring covers
 * why one bot's users never see another bot's data; this is the other
 * half: getting a *new* bot to begin with).
 *
 * Deliberately a file-writing CLI, not a button inside a running server:
 * spawning and supervising a whole new OS process from inside another one
 * is the fragile path, and lands right on the "local worker keeps dying"
 * problem this project just fixed in `start.bat`. Every bot's actual
 * uptime story — `start-<name>.bat` locally, systemd in production — stays
 * exactly the same as `bot-1`'s already is. Nothing here touches the login
 * system: `admin/session-cookie.ts`, `admin/users-store.ts` and
 * `admin/passwords.ts` are untouched, and a new bot's own admin/user
 * accounts still seed themselves the first time IT runs, same as always.
 */

const USAGE = `
Provisions a new, fully separate bot: config/bots/<name>.json + a
start-<name>.bat on its own port. Never touches an existing bot's config,
session, or login files.

  deno run -A apps/worker/src/cli/provision-bot.ts --name <slug>

Options
  --name <slug>   Required. Becomes the botId and the config/launcher
                  filename. Lowercased; anything but a-z, 0-9 and "-"
                  becomes "-". Must not already exist.
`.trim();

const BOTS_DIR = 'config/bots';
const EXAMPLE_CONFIG_NAME = 'bot-1.example.json';
const BASE_PORT = 8792; // 8791 is bot-1's own default, in start.bat.
const RESERVED_PORTS: ReadonlySet<number> = new Set([8791]);

export const errorMessage = (err: unknown): string =>
  err instanceof Error ? err.message : String(err);

export function sanitizeSlug(raw: string): string {
  const slug = raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  if (slug.length === 0) {
    throw new ConfigError(`--name "${raw}" has no usable characters (a-z, 0-9, -)`, { raw });
  }
  return slug;
}

/** Every port a generated `start-*.bat` in `root` already claims, by regex
 * on its `set PORT=<n>` line — no separate registry file to fall out of
 * sync with reality. */
export async function usedPorts(root: string): Promise<Set<number>> {
  const used = new Set<number>(RESERVED_PORTS);
  for await (const entry of Deno.readDir(root)) {
    if (!entry.isFile || !entry.name.startsWith('start-') || !entry.name.endsWith('.bat')) {
      continue;
    }
    const text = await Deno.readTextFile(`${root}/${entry.name}`);
    const match = text.match(/^set PORT=(\d+)/m);
    if (match?.[1] !== undefined) used.add(Number(match[1]));
  }
  return used;
}

export function nextFreePort(used: ReadonlySet<number>): number {
  let port = BASE_PORT;
  while (used.has(port)) port += 1;
  return port;
}

function botConfigContent(slug: string, exampleJson: string): string {
  const raw = JSON.parse(exampleJson) as Record<string, unknown>;
  const next = { ...raw, botId: slug, ownerId: `owner-${slug}`, dedicatedRooms: [] };
  return `${JSON.stringify(next, null, 2)}\n`;
}

function launcherBatContent(slug: string, configPath: string, port: number): string {
  // Same shape as the repo's own start.bat (deno/config checks, the
  // supervisor loop that fixed "the local worker keeps dying"), just
  // pointed at this bot's own config and port. Sessions and operator accounts
  // are both namespaced per bot, so a local launcher has the same isolation
  // boundary as the production systemd instance.
  return `@echo off
rem ASCII ONLY. Do not put non-ASCII text in this file.
rem Generated by provision-bot.ts for bot "${slug}" -- do not hand-edit the
rem CONFIG/PORT lines, re-run the provisioner instead.

setlocal
cd /d "%~dp0"

set CONFIG=${configPath}
set SESSIONS_DIR=.sessions
set USERS_FILE=.control\\bot-users\\${slug}.json
set PORT=${String(port)}

where deno >nul 2>&1
if errorlevel 1 (
    echo [x] deno not found on PATH.
    echo     Install: irm https://deno.land/install.ps1 ^| iex
    pause
    exit /b 1
)

if not exist "%CONFIG%" (
    echo [x] %CONFIG% not found -- was it moved or deleted?
    pause
    exit /b 1
)

echo Starting local worker: %CONFIG%  (sessions: %SESSIONS_DIR%, port: %PORT%)
echo Opening http://localhost:%PORT%/account/login
echo Press Ctrl+C to stop for real.
echo.

start "" "http://localhost:%PORT%/account/login"

:run
deno task serve --config "%CONFIG%" --sessions-dir "%SESSIONS_DIR%" --users-file "%USERS_FILE%" --port %PORT% %*
echo.
echo [i] worker stopped -- restarting in 3s (Ctrl+C, then Y, to quit for real)
timeout /t 3 /nobreak >nul
goto run

endlocal
`;
}

export interface ProvisionResult {
  slug: string;
  configPath: string;
  batPath: string;
  port: number;
}

/**
 * Does the actual work, relative to `root` — a plain parameter (rather than
 * always the process's own cwd) so this is directly testable against a temp
 * directory, the same shape as `RulesStore`/`UsersStore` taking an explicit
 * path instead of assuming where they live.
 */
export async function provisionBot(opts: { name: string; root: string }): Promise<
  ProvisionResult
> {
  const slug = sanitizeSlug(opts.name);
  const configPath = `${BOTS_DIR}/${slug}.json`;
  const batPath = `start-${slug}.bat`;

  const absoluteConfigPath = `${opts.root}/${configPath}`;
  const alreadyExists = await Deno.stat(absoluteConfigPath).then(() => true).catch(
    (err: unknown) => {
      if (err instanceof Deno.errors.NotFound) return false;
      throw err;
    },
  );
  if (alreadyExists) {
    throw new ConfigError(`${configPath} already exists — pick a different --name`, {
      configPath,
    });
  }

  const examplePath = `${opts.root}/${BOTS_DIR}/${EXAMPLE_CONFIG_NAME}`;
  const exampleJson = await Deno.readTextFile(examplePath).catch((err: unknown) => {
    throw new ConfigError(`cannot read ${examplePath}: ${errorMessage(err)}`, {
      path: examplePath,
    });
  });
  const port = nextFreePort(await usedPorts(opts.root));

  await Deno.writeTextFile(absoluteConfigPath, botConfigContent(slug, exampleJson));
  await Deno.writeTextFile(`${opts.root}/${batPath}`, launcherBatContent(slug, configPath, port));

  return { slug, configPath, batPath, port };
}

async function main(): Promise<number> {
  const flags = parseArgs(Deno.args, { string: ['name'], boolean: ['help'] });
  if (flags.help) {
    writeLine(USAGE);
    return 0;
  }
  if (typeof flags.name !== 'string' || flags.name.trim().length === 0) {
    throw new ConfigError('--name is required (see --help)');
  }

  const result = await provisionBot({ name: flags.name, root: '.' });

  writeLine('');
  writeLine(`bot          : ${result.slug}`);
  writeLine(`config       : ${result.configPath}`);
  writeLine(`launcher     : ${result.batPath}`);
  writeLine(`port         : ${String(result.port)}`);
  writeLine('');
  writeLine(
    `Run ${result.batPath} to start it, then open http://localhost:${
      String(result.port)
    }/account/login`,
  );
  writeLine('First run seeds its own admin/Root@77# account — same as every bot does.');
  writeLine('');
  return 0;
}

if (import.meta.main) {
  try {
    Deno.exit(await main());
  } catch (err: unknown) {
    writeErr(`provision-bot failed: ${errorMessage(err)}`);
    Deno.exit(1);
  }
}
